### ISSUE TITLE
Allow `output` function to break the compression/decompression?

### ISSUE THREAD

**Issue by spacewander** [hamishforbes/lua-ffi-zlib#4]
In one case, we need to write the compressed output to a file. If the writing is failed, we will stop compression, and report the error as soon as possible. To achieve this behavior, currently we 
have to check the error twice: at the beginning of the `input` function and after the `inflateGzip`.

However, if this library allow to break the compression/decompression in the `output` function, like this:

```lua
local output = function(data)
      local ok, err = f:write(data)
      if not ok then
            return nil, err
      end
end
```

we only need to check the error once right after where it occurs.

Would you like to introduce this feature? I will submit a PR.

**Comment by hamishforbes** [comment]
Yep that sounds like a good improvement, PR would be awesome!
